version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment: 
      MONGO_INITDB_ROOT_USERNAME: golist
      MONGO_INITDB_ROOT_PASSWORD: qwertyasdfghzxcvbn123456
    ports:
      - 27010:27017
    volumes:
      - ./mongo_data:/data/db